### ISSUE TITLE
file_name and file_time are required by nxvalidate but not by NXroot

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/cnxvalidate#24]
nxvalidate requires file_name and file_time as attributes of NXroot:

https://github.com/nexusformat/cnxvalidate/blob/master/src/nxvmainloop.c#L53-L74

However, these attributes are marked as optional in NXroot:
http://download.nexusformat.org/doc/html/classes/base_classes/NXroot.html

Are they optional?  If not, shouldn't the NXroot spec and the application definitions note this?

**Comment by yayahjb** [comment]
Dear Aaron,
  Making them mandatory for everybody is a big political decision, but we
certainly should make them explicitly mandatory for NXmx.
  Regards,
    Herbert

**Comment by phyy-nx** [comment]
@yayahjb why should we make them explicitly mandatory for NXmx?

**Comment by yayahjb** [comment]
Because time and file names are wonderful for disentangling a mess of
datasets -- Herbert

**Comment by phyy-nx** [comment]
Hm.  Well, I think that could be a proposal for NXmx.  What about fixing the 'bug' in nxvalidate where it is requiring something that (at present) isn't required?

**Comment by yayahjb** [comment]
Only if I add them as required to NXmx at the same time -- indeed, I will
do just that in the HDRMX/definitions and HDRMX/cnxvalidate forks.  That
will insulate us from any impact as the general change is considered.

**Comment by phyy-nx** [comment]
From code camp, it would be better if file_name and file_time could somehow be marked as 'recommended' (instead of optional vs. required), and that nxvalidate could then be run with various strictness levels.  See for example how punx (sp? @prjemian) has scoring abilities that range from -100000 (failing) to 0 (barely passing) to 100 (very good).

**Comment by mkoennecke** [comment]
Missing file_time and file_name file attributes have been reduced to a warning.

**Comment by vasole** [comment]
Please take into account an issue I have just opened for information purposes.

https://github.com/nexusformat/definitions/issues/836

**Comment by vasole** [comment]
The message is to keep the total number of mandatory NXroot attributes as small as reasonable (a maximum of 4 would be best to provide some freedom to end users)

https://github.com/h5py/h5py/issues/1641

**Comment by vasole** [comment]
From my side the message has been passed. I close the issue.

**Comment by vasole** [comment]
Sorry, wrong issue!

**Comment by mkoennecke** [comment]
Re-closed as reopened by mistake
