### ISSUE TITLE
depends_on . throws an error

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/cnxvalidate#25]
For NXmx, which has an NXdetector with a depends_on attribute, if that attribute is set to `.`, then nx validate throws this error:

Cannot even find the starting point of the depends_on chain

Instead it should accept `.` since in some cases the full depends_on chain is specified elsewhere.

**Comment by yayahjb** [comment]
Details please.  Which cnxvalidate, which data, what Cnxvalidate option?

**Comment by phyy-nx** [comment]
Here's the example data:
https://github.com/nexusformat/exampledata/blob/master/DLS/reflections/hdf5/thaumatin_integrated.nxs

I used the master of cnxvalidate with this command like this one:
nxvalidate -l $NEXUS/definitions thaumatin_integrated.nxs

Note, the thaumatin_integrated.nxs file in master has a lot of other validation problems. I have a version which has nearly no validation problems I'm about to add to nexusformat/example_data#7, but still has the problem from this issue.

**Comment by mkoennecke** [comment]
Hi Herbert and Aaron,


Am 28.01.2020 um 19:04 schrieb Herbert J. Bernstein <notifications@github.com<mailto:notifications@github.com>>:

Details please. Which cnxvalidate, which data, what Cnxvalidate option?

On Tue, Jan 28, 2020 at 11:55 AM Aaron S. Brewster <notifications@github.com<mailto:notifications@github.com>>
wrote:

> For NXmx, which has an NXdetector with a depends_on attribute, if that
> attribute is set to ., then nx validate throws this error:
>
> Cannot even find the starting point of the depends_on chain
>
> Instead it should accept . since in some cases the full depends_on chain
> is specified elsewhere.
>

???? I believe that in this case, cnxvalidate is right. A NXdetector without a depends_on chain is floating around in an unknown
position in space, may be around Neptune? In your use case, where the depends_on chain ist stored somewhere else, the depends_on
on NXdetector should point to the first entry of elsewhere.


Best Regards,

      Mark Koennecke

**Comment by zjttoefs** [comment]
I think it should be valid to put the detector in the sample position, which is what "." says. That makes both cnxvalidate and the file wrong in a way. The file should for sure not claim something that is not true.

I assume the location of the pixels is specified either in detector modules or somewhere. Legal according to the definitions, but not obvious.

**Comment by yayahjb** [comment]
Dear Mark,
  The subtle problem has to do with multi-module detectors in which there
may be more than one axis chain,
one for each module.  Aaron's suggested wording is intended to allow for
that case.
  Regards,
    Herbert

**Comment by phyy-nx** [comment]
Right, this is all for the multi-module case, especially when none of the modules are related to each other.  In this case, having a depends_on field at the detector level doesn't mean anything, but it is still required in NXmx.

**Comment by zjttoefs** [comment]
I don't think it is great that NXmx requires that. But would it make sense to point to the depends_on of one of the modules (first one, largest one, or something sane)?

**Comment by phyy-nx** [comment]
I don't think so, since each module doesn't refer to the other ones.  My preferred solution is to make the depends_on field in NXdetector in NXmx optional since it only seems to be useful for a 1 panel detector.

**Comment by mkoennecke** [comment]
Hi,

Am 30.01.2020 um 17:36 schrieb Aaron S. Brewster <notifications@github.com<mailto:notifications@github.com>>:


I don't think so, since each module doesn't refer to the other ones. My preferred solution is to make the depends_on field in NXdetector in NXmx optional since it only seems to be useful for a 1 panel detector.


I beg to disagree. A given detector may consist of many modules. But then there are collective properties of the whole detector assembly which need to
be stored. Also, you might want to move the whole detector assembly. And then a depends_on chain for the whole detector assembly is required. With the
modules referring to it.

Best Regards,

     Mark Koennecke

**Comment by phyy-nx** [comment]
Closed in #28
