### ISSUE TITLE
failed to find application definition

### ISSUE THREAD

**Issue by prjemian** [nexusformat/cnxvalidate#32]
Using the [`cnxvalidate-web`](https://bmaranville.github.io/cnxvalidate-web/) tool, it is shown that for the [`writer_1_3.hdf5`](https://manual.nexusformat.org/examples/h5py/writer_1_3.html) example file that 

```
Cannot validate Scan, failed to find application definition
```

which is reported as an error.  I believe this message originates from this code: https://github.com/nexusformat/cnxvalidate/blob/4a21051c45b63fd6b4f07f6eb7ce24c70ddef932/src/nxvmainloop.c#L248-L256

This is incorrect.  An NXentry is not required to be governed by an application definition nor is it required to have a NXsubentry group.

**Comment by prjemian** [comment]
### Is application definition required in NXentry?

The [`definition` field in `NXentry`](
https://github.com/nexusformat/definitions/blob/a10bd5e8323ea57a03ee01e49f16eb645b999bb8/base_classes/NXentry.nxdl.xml#L130-L144) is optional by default since it does not define `optional=False`.

```xml
	<field name="definition">
		<doc>
			(alternate use: see same field in :ref:`NXsubentry` for preferred)
			
			Official NeXus NXDL schema to which this entry conforms.
			
			This field is provided so that :ref:`NXentry` can be the overlay position
			in a NeXus data file for an application definition and its 
			set of groups, fields, and attributes.
			
			*It is advised* to use :ref:`NXsubentry`, instead, as the overlay position.
		</doc>
		<attribute name="version"><doc>NXDL version number</doc></attribute>
		<attribute name="URL"><doc>URL of NXDL file</doc></attribute>
	</field>
```
### Is NXsubentry required if `definition` field is not found?

The [`NXsubentry` group in `NXentry`](https://github.com/nexusformat/definitions/blob/a10bd5e8323ea57a03ee01e49f16eb645b999bb8/base_classes/NXentry.nxdl.xml#L220) is optional by default.

```xml
	<group type="NXsubentry" />
```

since it does not define `optional=False`.

### optional by default

This is a rule that has not been expressed in the NXDL Schema.  In base classes, all fields and groups are optional by default (unless marked `optional=False`).  In application definitions, all fields and groups are required by default (unless marked `optional=True`).

**Comment by mkoennecke** [comment]
Hmmhh, you are right about the optional stuff and such. But in this stage of the code no application definition has been found and thus we can only do a very basic validation. This situation ought to be reported. Would this issue be fixed by relaxing the message from an error to a warning?

**Comment by prjemian** [comment]
Yes

**Comment by mkoennecke** [comment]
Fixed.
